---
# Check if CI_COMMIT_TAG is defined (only when making a release) to disable devel repositories
# that contain install dependencies
release_status: '{{ True if lookup("env", "CI_COMMIT_TAG")
                         else False }}'

# set to package name to avoid installing packetfence-release
# from inverse.ca website (already installed based on pipeline
# artifacts)
packetfence_install__centos_release_rpm: 'packetfence-release'

packetfence_install__centos:
  repo: '{{ "packetfence" if release_status|bool
                          else "packetfence-devel" }}'

packetfence_install__deb:
  repos: '{{ ["debian"] if release_status|bool
                        else ["debian","debian-devel"] }}'


# config
# need to be defined here to be available to plays
# that not include packetfence_install role
packetfence_install__database_root_pass: secret

packetfence_install__fingerbank_setting:
  upstream:
    api_key: '{{ lookup("env", "FINGERBANK_API_KEY") }}'


packetfence_install__configuration:

      - name: 'pf.conf'
        sections:

          - name: 'database'
            settings:

              - name: 'pass'
                value: '{{ packetfence_install__database_pass }}'

          - name: 'advanced'
            settings:

              - name: 'api_inactivity_timeout'
                value: '12h'

              - name: 'configurator'
                value: '{{ packetfence_install__configurator_status }}'

              - name: 'pffilter_processes'
                value: '1'

              - name: 'pfperl_api_processes'
                value: '1'

          - name: "interface {{ packetfence_install__mgmt_interface['id'] }}"
            settings:

              - name: 'ip'
                value: "{{ packetfence_install__mgmt_interface['ip'] }}"

              - name: 'mask'
                value: "{{ packetfence_install__mgmt_interface['mask'] }}"

              - name: 'type'
                value: "{{ packetfence_install__mgmt_interface['type'] }}"

      - name: 'pfconfig.conf'
        sections:

          - name: 'general'
            settings:

              - name: 'backend'
                value: 'mysql'

          - name: 'mysql'
            settings:

              - name: 'host'
                value: 'localhost'

              - name: 'user'
                value: '{{ packetfence_install__database_default_user }}'

              - name: 'pass'
                value: '{{ packetfence_install__database_pass }}'

              - name: 'db'
                value: '{{ packetfence_install__database_db }}'

              - name: 'port'
                value: '3306'

              - name: 'table'
                value: 'keyed'

      - name: 'pfqueue.conf'
        sections:

          - name: 'pfqueue'
            settings:

              - name: 'workers'
                value: '1'
